#!/bin/sh

cat UnsortedPackagePaths.txt | grep audio > audio.txt
cat UnsortedPackagePaths.txt | grep archivers > archivers.txt
cat UnsortedPackagePaths.txt | grep benchmarks > benchmarks.txt
cat UnsortedPackagePaths.txt | grep biology > biology.txt
cat UnsortedPackagePaths.txt | grep cad > cad.txt
cat UnsortedPackagePaths.txt | grep chat > chat.txt
cat UnsortedPackagePaths.txt | grep comms > comms.txt
cat UnsortedPackagePaths.txt | grep converters > converters.txt
cat UnsortedPackagePaths.txt | grep databases > databases.txt
cat UnsortedPackagePaths.txt | grep devel > devel.txt
cat UnsortedPackagePaths.txt | grep editors > editors.txt
cat UnsortedPackagePaths.txt | grep emulators > emulators.txt
cat UnsortedPackagePaths.txt | grep filesystems > filesystems.txt
cat UnsortedPackagePaths.txt | grep finance > finance.txt
cat UnsortedPackagePaths.txt | grep fonts > fonts.txt
cat UnsortedPackagePaths.txt | grep games > games.txt
cat UnsortedPackagePaths.txt | grep geography > geogtraphy.txt
cat UnsortedPackagePaths.txt | grep graphics > graphics.txt
cat UnsortedPackagePaths.txt | grep ham > ham.txt
cat UnsortedPackagePaths.txt | grep inputmethod > inputmethod.txt
cat UnsortedPackagePaths.txt | grep lang > lang.txt
cat UnsortedPackagePaths.txt | grep mail > mail.txt
cat UnsortedPackagePaths.txt | grep math > math.txt
cat UnsortedPackagePaths.txt | grep mbone > mbone.txt
cat UnsortedPackagePaths.txt | grep misc > misc.txt
cat UnsortedPackagePaths.txt | grep multimedia > multimedia.txt
cat UnsortedPackagePaths.txt | grep net > net.txt
cat UnsortedPackagePaths.txt | grep news > news.txt
cat UnsortedPackagePaths.txt | grep parallel > parallel.txt
cat UnsortedPackagePaths.txt | grep pkgtools > pkgtools.txt
cat UnsortedPackagePaths.txt | grep print > print.txt
cat UnsortedPackagePaths.txt | grep security > security.txt
cat UnsortedPackagePaths.txt | grep shells > shells.txt
cat UnsortedPackagePaths.txt | grep sysutils > sysutils.txt
cat UnsortedPackagePaths.txt | grep textproc > textproc.txt
cat UnsortedPackagePaths.txt | grep time > time.txt
cat UnsortedPackagePaths.txt | grep wm > wm.txt
cat UnsortedPackagePaths.txt | grep www > www.txt
cat UnsortedPackagePaths.txt | grep x11 > x11.txt